### ISSUE TITLE
BUG: not reactive client when server delete fields

### ISSUE THREAD

**Issue by 2ducanhpham** [inProgress-team/react-native-meteor#293] opened 2017-12-06 06:53 UTC
I fixed, you can merge if need

```
// convert from message.cleared to message.fields
    Data.ddp.on("changed", message => {
      if ( message.cleared && message.cleared.length > 0 ) {
        message.fields = message.fields || {};
        message.cleared.forEach((item) => {
          message.fields[item] = undefined;
        });
      }
      Data.db[message.collection] && Data.db[message.collection].upsert({_id: message.id, ...message.fields});
    });
```

![screen shot 2017-12-06 at 10 47 10 am](https://user-images.githubusercontent.com/14899775/33648498-c2de4e6a-da8c-11e7-9447-d4ebc2b06d05.png)

In file Meteor.js

**Comment by Artemnsk** [comment] 2017-12-18 11:20
@2ducanhpham 
Man you saved my life.

**Comment by jamesloper** [comment] 2018-02-12 18:35
Thanks s lot @2ducanhpham. Can we get this merged any time soon?

**Comment by naturom** [comment] 2018-04-11 10:39
By updating a document field value in db, the changes is not reflected in client side in real time as well.... is this a bug?

**Comment by odesey** [comment] 2018-04-15 02:36
Having the same issue as @naturom 

When I update a document in the database, it is not reflected on the client even though I receive "new" documents from the server reactively.

The following `console.log` never even gets called in `Meteor.js`

```javascript
    Data.ddp.on("changed", message => {
      console.log(message);
      Data.db[message.collection] && Data.db[message.collection].upsert({_id: message.id, ...message.fields});
    });
```

Running Meteor 1.6, React Native 0.51.0

Any idea what might be causing this?

**Comment by naturom** [comment] 2018-04-15 02:43
@odesey Actually it was my mistake, the changed event in my case did trigger and data reactively reflected perfectly. It was actually caused by my custom component that did not do the update during props changed (only during mounted) :P

**Closed** 2018-08-06 03:12 UTC
