### ISSUE TITLE
Miss spelling subscribe with suscribe

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#2] opened 2016-02-13 05:04 UTC
Please fix the miss spelling of suscribe to subscribe. this will lead to chaos :)
thanks

**Comment by Mokto** [comment] 2016-02-18 13:30
Oh right ! Fixing it today.

**Comment by Mokto** [comment] 2016-02-18 14:18
It is now fixed.
Thank you for warning me :)

https://github.com/inProgress-team/react-native-meteor/releases/tag/0.5.0

**Comment by radiegtya** [comment] 2016-02-19 03:54
Good Job, Thanks @Mokto

**Comment by radiegtya** [comment] 2016-02-19 10:51
Get a new Bug after updating to latest "react-native-meteor@0.5.0". Could not find preset es-2015.
Then I am trying to install this packages:
- babel-preset-es2015
- babel-preset-react
- babel-preset-stage-0
the error gone, but there are another error.

could not find EventEmitter. I think this is causes by ddp.js latest update. Please Fix this

**Comment by Mokto** [comment] 2016-02-19 14:04
What is you React-native version ?

**Comment by radiegtya** [comment] 2016-02-20 09:20
I am using 0.19.0 and 0.20.0. Both of them give that error message

**Comment by radiegtya** [comment] 2016-02-21 11:38
Any update to this?

**Comment by Mokto** [comment] 2016-02-21 16:28
Still not, I'm thinking about it today.

Are you using webpack ?

**Comment by radiegtya** [comment] 2016-02-22 07:10
No, I am not.
I am only using _react-native-cli_ like in official RN suggestions.

**Comment by Mokto** [comment] 2016-02-22 14:36
I'm sorry but I am unable to reproduce your bug. I tried to react-native init a new project, but when installing react-native-meteor, I have no issue.

Could you please :
- Let me know the exact workflow to reproduce.
- OR Set up a Github repo where I can reproduce

Thanks

**Comment by radiegtya** [comment] 2016-02-23 14:18
What is your RN version? Tomorrow I'll try reinstalling my RN first

**Comment by Mokto** [comment] 2016-02-23 14:46
My most used version is 0.19 but I tried with a react-native init Projet (0.20).

**Comment by radiegtya** [comment] 2016-02-24 08:45
I see what's the culprit.

1. We can't use NPM v 4.x use 5.x instead for latest RN 0.19+
2. If you are already using old version of NPM update it to latest version with NVM then reinstall react-native-cli
3. Install this babel dependencies after init a project
- npm i --save babel-preset-es2015
- npm i --save babel-preset-react
- npm i --save babel-preset-stage-0

Oh ya, in Readme please add this line at header (or if I have time I'll send PR)
import meteor from 'react-native-meteor';
 
Thanks and I'll closing this.

**Comment by Mokto** [comment] 2016-02-24 13:56
Thank you !

To be clear, I'm using node v4 and npm v2, so I do not really understand what is your problem ^^

I'm adding `import meteor from 'react-native-meteor';` in the README !

**Comment by Mokto** [comment] 2016-02-25 23:43
Ok I found why it's not working, I will be adding this presets to react-native-meteor plugin.

**Comment by Mokto** [comment] 2016-03-02 00:16
Fixed in 0.6.2 ;)

**Closed by Mokto** 2016-03-02 00:16 UTC
