### ISSUE TITLE
Issue to update 

### ISSUE THREAD

**Issue by txs** [inProgress-team/react-native-meteor#183] opened 2016-12-27 18:14 UTC
I'm having a issue about this.db.batchedUpdates is not a function inside WriteTransaction.js
And also _.all is not a function

Please help

**Comment by spencercarli** [comment] 2016-12-27 18:51
Possibly related: 

- https://github.com/inProgress-team/react-native-meteor/issues/76
- https://github.com/inProgress-team/react-native-meteor/issues/77

I believe the issues comes from this line: https://github.com/inProgress-team/react-native-meteor/blob/874112d5e73782e68446fbb1f5b502f1b0ecda5d/src/Data.js#L9

RN source where it was defined: https://github.com/facebook/react-native/blob/3683beb88ab3233038ac32b9c33112d537478088/Libraries/Renderer/src/renderers/native/ReactNative.js#L41

@txs what version of React Native are you using? I wonder if `ReactNative.unstable_batchedUpdates` is no longer valid.

@Mokto I checked out the git blame and looks like you made that change - any insight on this?

**Comment by txs** [comment] 2016-12-28 08:18
RN 0.39.2

**Comment by txs** [comment] 2016-12-28 08:19
I'm using the ws not wss

**Comment by txs** [comment] 2016-12-28 08:21
the line is in WriteTransaction.js "return this.db.batchedUpdates((function(_this) {" line 75

**Comment by txs** [comment] 2017-01-28 02:23
@spencercarli  Do you know how to solve it?

**Comment by spencercarli** [comment] 2017-01-29 20:13
@txs no sorry I don't. I'm using the latest React Native and latest version of this packages without any issues.

**Comment by txs** [comment] 2017-04-18 18:43
I still have this issue and the batchupdate seems deprecated

**Comment by dtruel** [comment] 2017-05-11 19:05
I'm having this issue in .45.0-rc.0.  When I downrgrade to .44 it goes away

**Comment by txs** [comment] 2017-05-13 19:48
I think it's a issue with minimongo 0.48

**Comment by txs** [comment] 2017-05-13 19:54
I'm using react native 0.42, I'll try upgrade to 0.44

**Comment by txs** [comment] 2017-05-13 20:20
I think we have to change it to unstable_batchedUpdate

**Comment by txs** [comment] 2017-05-15 06:33
Can require("reactUpdates") solve the issue?

dtruel <notifications@github.com> 於 2017年5月12日 週五 上午3:05寫道：

**Comment by dtruel** [comment] 2017-05-15 17:40
Hey @txs, I don't have a lot of extra time right now so I'm going to wait to test till .45 comes out of rc because it makes upgrading quicker.  Thanks for the tip though.

**Comment by anhtuank7c** [comment] 2017-06-08 04:10
0.45.0 is now official and still got this error :(

**Comment by txs** [comment] 2017-06-08 07:59
Are you using the react native or react native web?

Nguyễn Anh Tuấn <notifications@github.com> 於 2017年6月8日 週四 下午12:10寫道：

**Comment by anhtuank7c** [comment] 2017-06-08 08:14
@txs I use React Native.

**Comment by steven-tib** [comment] 2017-06-09 00:10
I'm having the same issue, 
I just tried to update to 0.45 and also have react 16 alpha dependency
Anyone found a way to fix it with 0.45 or should I downgrade to 0.44?

**Comment by anhtuank7c** [comment] 2017-06-09 01:33
@steven-tib 
I have to use RN 44 instead of 45.

**Comment by steven-tib** [comment] 2017-06-09 07:59
@anhtuank7c thanks, I'll switch back to 0.44 then

**Comment by Nauzer** [comment] 2017-06-09 13:14
I'm having the same issue. Downgrading to 0.44 has helped.
Is this an issue of React-Native or with this package?

**Comment by wenzelmk** [comment] 2017-06-12 20:10
I'm having the same problem, and I'm having trouble figuring out how to downgrade to 0.44. Could anyone point me in the direction of some instructions on how to downgrade?

**Comment by Nauzer** [comment] 2017-06-12 20:48
I think you can just remove your node_modules folder, update the version in your package.json and run npm install.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Nauzer** [comment] 2017-06-13 10:42
@steven-tib to avoid staying stuck on 0.44, I was looking into fixing this.
Haven't gotten a lot further though. How about you?

**Comment by Nauzer** [comment] 2017-06-13 12:48
I was able to get it to work by using ReactDOM. Which is ofcourse not a real solution. Shouldn't need ReactDOM dependency in a react-native project. Anyway sharing it here to get people going until a more structural solution is found.

@txs @spencercarli @Mokto Any ideas?

_Data.js_:
``` 
// line 
import ReactDOM from 'react-dom';
...
// line 9 change to:
db.batchedUpdates = ReactDOM.unstable_batchedUpdates;

```
Make sure to add ReactDOM to your project dependencies.

A working branch can be found here:
https://github.com/Nauzer/react-native-meteor/commit/4c18bbe1aeaec6b44deb574b811617f382c46c0f

**Comment by steven-tib** [comment] 2017-06-13 15:58
@Nauzer I haven't checked this further sorry, just downgraded for now. Thanks for trying to fix it though

**Comment by spencercarli** [comment] 2017-06-13 16:01
Been working on this all morning. Having trouble upgrading to 0.45 - my app crashes whenever I turn remote debugging on 🙄

**Comment by Nauzer** [comment] 2017-06-13 17:57
@spencercarli same here. 
All I could do was use ReactDOM to replace it as a hack... Let's hope someone at FB looks at the react-native issue I posted.

For your issue --> Had this same issue. Here's helped for me:

- remove node_modules
- `npm install`
- clear build in xcodeproject/workspace (Shift + Cmd + K)
- clear build folder in xcodeproject/workspace (Alt + Shift + Cmd + K)
- `react-native run-ios`

Also upgrading to 0.45.1 made everything a lot better in terms of build stability. Doesn't solve the issue though.

@steven-tib Downgrade doesn't do for me because of some issue with react-native-maps. Let's see.

**Comment by spencercarli** [comment] 2017-06-13 18:24
@Nauzer the issue I had (I think) was related to react-native-maps. I was on 0.43 then upgraded to 0.44, maps didn't work so I unlinked and relinked react-native-maps which fixed everything in 0.44, then went to 0.45. Now batchedUpdates 😄 

react-dom crashes my app for some reason. Hopefully I can figure it out!

**Comment by Nauzer** [comment] 2017-06-13 18:48
What kind of error are you getting? I included react-dom@16.0.0-alpha.12 as a dependency of my react-native-meteor for not directly in my project.

**Comment by spencercarli** [comment] 2017-06-13 23:10
@Nauzer I was (stupidly) using the wrong version of react-dom - completely neglected to see your working branch the branch you linked to! Thanks for providing that!

You just stepped in at a lucky time 😄 - this issue just started hitting most people (except OP) in the last few days with the release of RN v0.45 (my email has been inundated with questions about it)

Other than that there haven't been many issues (at least from my experience)

**Comment by edmundkwok** [comment] 2017-06-14 05:00
Looks like `'ReactNativeInternals'` (which exported `unstable_batchedUpdates`) was removed from being exposed as per:

https://github.com/facebook/react-native/commit/f3dbddcf2bdc0e4f49dd6f5220360b5ff383e16f#diff-834d77988fd4294e13e3e35533b3e248L161

While waiting for an update on https://github.com/facebook/react-native/issues/14490, I did the following change in `react-native-meteor` to import ReactNativeInternals directly:

_Data.js_

```diff
// Line 1
- import ReactNative from 'react-native';
+ const ReactNative = require('react-native/Libraries/Renderer/src/renderers/native/ReactNative');
```

Seems like it's working, but may not be the best long term fix.

What do you guys think?

**Comment by Nauzer** [comment] 2017-06-14 06:31
Thanks @edmundkwok I was on this trail yesterday by using ReactNativeStack/ReactNativeFiber - didn't get it to work. Good job!
One thing - I would suggest sticking to ES6 imports.

_Data.js_:
```diff
// line 1
- import ReactNative from 'react-native';
+import ReactNative from 'react-native/Libraries/Renderer/src/renderers/native/ReactNative'
```
Maybe you want to post your solution to the [RN Issue](https://github.com/facebook/react-native/issues/14490) to add some context?

**Comment by edmundkwok** [comment] 2017-06-14 09:44
Thanks @Nauzer! Yes of course, we should stick to ES6 😉 

I have added a comment on https://github.com/facebook/react-native/issues/14490

**Comment by wenzelmk** [comment] 2017-06-15 19:18
@Nauzer Thanks for your previous help! I have a question that might be kind of dumb, but where should I be adding the change recommended to @edmundkwok to? (I'm very new to coding + react-native in general).

**Comment by Nauzer** [comment] 2017-06-15 21:32
Hi @wenzelmk 
Until we merge this in this repo somehow (for that we need to confirm the issue in the react-native repo link to above) you can use my branch.

`git clone https://github.com/Nauzer/react-native-meteor.git` 
in a directory of your liking.

In your project's package.json replace react-native-meteor with the relative path to the directory where you cloned it. I did it in my project's parent folder.

```diff
-"react-native-meteor": "^1.0.3",
+"react-native-meteor": "../react-native-meteor"
```
remove the node_modules folder

`npm install`

And you should be good to go :)

**Comment by abser** [comment] 2017-06-16 08:08
Thanks @Nauzer .
It helps me as well.

**Comment by ujwal-setlur** [comment] 2017-06-20 00:28
Just ran into this as well. Downgrading to 0.44. Hopefully, I won't run into any issues on that path.

**Comment by ujwal-setlur** [comment] 2017-06-20 00:35
OK, downgrading to RN 0.44 worked for me. Hopefully, this will get resolved soon.

**Comment by Nauzer** [comment] 2017-06-20 05:40
I could do a PR  for this.
Automatic tests are failing but that is not a result of the change for this fix.

@noris666 Any suggestions?

**Comment by elie222** [comment] 2017-06-23 16:29
Or this:     `"react-native-meteor": "git://github.com/Nauzer/react-native-meteor.git"`,

**Comment by jasonnathan** [comment] 2017-07-01 16:14
@Nauzer, I tried using your branch and I'm getting another error, this time for *loginWithPassword*. (I could start a new issue, but not sure if it's related & issues are disabled on your branch)

`ExceptionsManager.js:63 _reactNativeMeteor2.default.loginWithPassword(...) is not a function`

**Comment by Nauzer** [comment] 2017-07-02 21:05
@jasonnathan i cant reproduce. Can you share your code?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ujwal-setlur** [comment] 2017-07-02 21:18
Any hope this will get merged into the official repo?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jasonnathan** [comment] 2017-07-03 01:38
Apologies @Nauzer, false alarm!

**Comment by Nauzer** [comment] 2017-07-03 06:39
@ujwal-setlur It was  already nerged. Will be pushed to npm somewhere today.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ujwal-setlur** [comment] 2017-07-03 14:55
Awesome!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nauzer** [comment] 2017-07-04 08:36
Merged to version 1.0.5. Closed.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-07-04 08:36 UTC

**Comment by ujwal-setlur** [comment] 2017-07-04 15:59
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by charpeni** [comment] 2017-07-06 17:19
@Nauzer in `react-native@0.46.0`, it has been renamed. :sweat:

```diff
-import ReactNative from 'react-native/Libraries/Renderer/src/renderers/native/ReactNative';
+import ReactNative from 'react-native/Libraries/Renderer/shims/ReactNative';
```

I'll send a PR.
